name: pytest (Docker env)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t gasw_workflow .
    - name: Run pytest in docker env
      run: docker run -v $(pwd):/usr/src/gasw -w /usr/src/gasw -e GAMMA_VER=20221129 -t gasw_workflow pytest --mypy
