name: Lint

on: [push, pull_request]

# TODO: Add flake8, shellcheck.
#       But the current code needs to be updated to pass them.
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable

